# Generated by Django 2.0.9 on 2018-10-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(default='tests.py', upload_to='uploads/'),
        ),
    ]
